name: data_layer
description: "Data layer package for project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1
homepage:

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  model_layer:
    path: ../model_layer

dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_lints: ^4.0.0
  analyzer_sm:
    path: ../analyzer_sm

flutter:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
