name: business
description: Package with Business Logic layer

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  get_it: ^8.0.0
  #hive: ^2.2.3
  #hive_flutter: ^1.1.0
  #firebase_core: ^2.10.0
  #firebase_auth: ^4.4.2
  #cloud_firestore: ^4.5.2
  #google_sign_in: ^6.1.0
  model:
    path: ../model
  data_sm:
    path: ../data_sm
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer_sm:
    path: ../analyzer_sm

flutter:
  uses-material-design: true
