name: model_layer
description: "Model layer package for project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1
homepage:

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  #hive: ^2.2.3
  #freezed: ^2.3.2
  #freezed_annotation: ^2.2.0
  #json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_lints: ^4.0.0
  #build_runner: ^2.3.3
  #json_serializable: ^6.6.2
  analyzer_sm:
    path: ../analyzer_sm

flutter:

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
