name: analyzer_sm
description: "Analyzer package for project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1
homepage:

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  pedantic_mono: ^1.29.0
  #dart_code_metrics:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  #uses-material-design: true